// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package provider

import (
	rock_peper_scissors2 "github.com/pt-suzuki/grpc_template/src/controllers/rock_peper_scissors"
	"github.com/pt-suzuki/grpc_template/src/domains/rock_peper_scissors"
	"github.com/pt-suzuki/grpc_template/src/provider/pb_provider"
)

// Injectors from wire.go:

func Wire() *Providers {
	translator := rock_peper_scissors.TranslatorImpl()
	service := rock_peper_scissors.ServiceImpl(translator)
	playGameResponder := rock_peper_scissors2.PlayGameResponderImpl()
	playGameAction := rock_peper_scissors2.PlayGameActionImpl(service, translator, playGameResponder)
	reportMatchResultsResponder := rock_peper_scissors2.ReportMatchResultsResponderImpl()
	reportMatchResultsAction := rock_peper_scissors2.ReportMatchResultsActionImpl(service, translator, reportMatchResultsResponder)
	rockPaperScissorsProvider := pb_provider.RockPaperScissorsProviderImpl(playGameAction, reportMatchResultsAction)
	providers := ProvidersImpl(rockPaperScissorsProvider)
	return providers
}
