// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: models/rock_paper_scissors/hand_shapes.proto

package rock_paper_scissors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// enumでグー、チョキ、パーを定義。
type HandShapes int32

const (
	HandShapes_HAND_SHAPES_UNKNOWN HandShapes = 0
	HandShapes_ROCK                HandShapes = 1
	HandShapes_PAPER               HandShapes = 2
	HandShapes_SCISSORS            HandShapes = 3
)

// Enum value maps for HandShapes.
var (
	HandShapes_name = map[int32]string{
		0: "HAND_SHAPES_UNKNOWN",
		1: "ROCK",
		2: "PAPER",
		3: "SCISSORS",
	}
	HandShapes_value = map[string]int32{
		"HAND_SHAPES_UNKNOWN": 0,
		"ROCK":                1,
		"PAPER":               2,
		"SCISSORS":            3,
	}
)

func (x HandShapes) Enum() *HandShapes {
	p := new(HandShapes)
	*p = x
	return p
}

func (x HandShapes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandShapes) Descriptor() protoreflect.EnumDescriptor {
	return file_models_rock_paper_scissors_hand_shapes_proto_enumTypes[0].Descriptor()
}

func (HandShapes) Type() protoreflect.EnumType {
	return &file_models_rock_paper_scissors_hand_shapes_proto_enumTypes[0]
}

func (x HandShapes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandShapes.Descriptor instead.
func (HandShapes) EnumDescriptor() ([]byte, []int) {
	return file_models_rock_paper_scissors_hand_shapes_proto_rawDescGZIP(), []int{0}
}

var File_models_rock_paper_scissors_hand_shapes_proto protoreflect.FileDescriptor

var file_models_rock_paper_scissors_hand_shapes_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61,
	0x70, 0x65, 0x72, 0x5f, 0x73, 0x63, 0x69, 0x73, 0x73, 0x6f, 0x72, 0x73, 0x2f, 0x68, 0x61, 0x6e,
	0x64, 0x5f, 0x73, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2a, 0x48, 0x0a, 0x0a, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68,
	0x61, 0x70, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x13, 0x48, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x48, 0x41,
	0x50, 0x45, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x52, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x41, 0x50, 0x45, 0x52,
	0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x43, 0x49, 0x53, 0x53, 0x4f, 0x52, 0x53, 0x10, 0x03,
	0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x74, 0x2d, 0x73, 0x75, 0x7a, 0x75, 0x6b, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72, 0x6f,
	0x63, 0x6b, 0x5f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x63, 0x69, 0x73, 0x73, 0x6f, 0x72,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_rock_paper_scissors_hand_shapes_proto_rawDescOnce sync.Once
	file_models_rock_paper_scissors_hand_shapes_proto_rawDescData = file_models_rock_paper_scissors_hand_shapes_proto_rawDesc
)

func file_models_rock_paper_scissors_hand_shapes_proto_rawDescGZIP() []byte {
	file_models_rock_paper_scissors_hand_shapes_proto_rawDescOnce.Do(func() {
		file_models_rock_paper_scissors_hand_shapes_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_rock_paper_scissors_hand_shapes_proto_rawDescData)
	})
	return file_models_rock_paper_scissors_hand_shapes_proto_rawDescData
}

var file_models_rock_paper_scissors_hand_shapes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_rock_paper_scissors_hand_shapes_proto_goTypes = []interface{}{
	(HandShapes)(0), // 0: models.HandShapes
}
var file_models_rock_paper_scissors_hand_shapes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_rock_paper_scissors_hand_shapes_proto_init() }
func file_models_rock_paper_scissors_hand_shapes_proto_init() {
	if File_models_rock_paper_scissors_hand_shapes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_rock_paper_scissors_hand_shapes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_rock_paper_scissors_hand_shapes_proto_goTypes,
		DependencyIndexes: file_models_rock_paper_scissors_hand_shapes_proto_depIdxs,
		EnumInfos:         file_models_rock_paper_scissors_hand_shapes_proto_enumTypes,
	}.Build()
	File_models_rock_paper_scissors_hand_shapes_proto = out.File
	file_models_rock_paper_scissors_hand_shapes_proto_rawDesc = nil
	file_models_rock_paper_scissors_hand_shapes_proto_goTypes = nil
	file_models_rock_paper_scissors_hand_shapes_proto_depIdxs = nil
}
